name: ğŸ—ï¸ Infra Deploy & Wake Up (07:00 BRT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # BotÃ£o Manual
  schedule:
    - cron: '0 10 * * *' # 10:00 UTC = 07:00 BRT

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  TF_VERSION: 1.13.5
  CLUSTER_NAME: hackathon-project-cluster-hackathon 

jobs:
  deploy-and-wake:
    name: Apply & Scale Up
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform 

    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ” Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ğŸ—ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: âš™ï¸ Terraform Init
        run: terraform init
      - name: ğŸš€ Terraform Apply
        run: terraform apply -auto-approve -input=false
      - name: â° Wake Up Services (Scale to 1)
        run: |
          echo "Acordando a infraestrutura..."
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service service-java --desired-count 1
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service service-csharp --desired-count 1
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service app-flutter --desired-count 1
          echo "ServiÃ§os iniciados! Aguarde uns minutos para o Health Check passar."
