name: üí∞ FinOps Check (Infracost)

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'terraform/**' 
permissions:
  contents: read
  pull-requests: write 
jobs:
  infracost:
    name: Estimate Cost
    runs-on: ubuntu-latest
    
    steps:
      - name: ‚¨áÔ∏è Checkout Code
        uses: actions/checkout@v4

      - name: üí∞ Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: üßÆ Run Infracost breakdown
        run: |
          infracost breakdown --path ./terraform \
                              --format json \
                              --out-file /tmp/infracost.json \
                              --usage-file ./terraform/infracost-usage.yml

      - name: üí¨ Post Cost Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          infracost comment github --path /tmp/infracost.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --pull-request ${{ github.event.pull_request.number }} \
                                   --behavior update
