name: ğŸ’° FinOps Check (Infracost)

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'terraform/**'
permissions:
  contents: read
  pull-requests: write 

jobs:
  infracost:
    name: Estimate Cost
    runs-on: ubuntu-latest
    
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ’° Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: ğŸ§® Run Infracost breakdown
        run: |
          infracost breakdown --path ./terraform \
                              --format json \
                              --out-file /tmp/infracost.json \
                              --usage-file ./terraform/infracost-usage.yml

      - name: ğŸ’¬ Post Cost Comment
        uses: infracost/actions/comment@v3
        with:
          path: /tmp/infracost.json
          behavior: update 
