name: üß® Terraform Destroy (NUKE)

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'ATEN√á√ÉO: Digite "DESTRUIR" para confirmar a exclus√£o total.'
        required: true
        default: ''

jobs:
  destroy-infra:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    # S√≥ roda se o usu√°rio digitou a palavra m√°gica
    if: github.event.inputs.confirmation == 'DESTRUIR'
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2' # Ajuste para sua regi√£o se for outra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # Opcional: Mostra o que vai ser deletado antes
      # - name: Terraform Plan Destroy
      #   run: terraform plan -destroy

      - name: üíÄ Terraform Destroy
        run: terraform destroy -auto-approve
